document:
  name: Linee Guidapiano di cessazione conservatori
  description: |
    Linee Guida per la stesura del piano di cessazione del servizio di conservazione dei documenti informatici
  tags:
    - "SPID"
