document:
  name: Linee Guida sul piano di cessazione conservatori
  description: |
    Linee Guida per la stesura del piano di cessazione del servizio di conservazione dei documenti digitali
  tags:
    - conservazione
    - conservazione sostitutiva
    - cessazione
    - eIDAS
